version: '3'

services:
  marklogic-server:
    image: store/marklogicdb/marklogic-server:9.0-11-dev-centos
    environment:
        - MARKLOGIC_INIT=true
        - MARKLOGIC_ADMIN_USERNAME=admin
        - MARKLOGIC_ADMIN_PASSWORD=admin
        - TZ=Europe/Prague
    ports:
     - 7997-8050:7997-8050

